== Final fields

Let us start with a definition:

****
*Definition*: We say a field is *effectively final* when it either has the modifier `final`, or it is not assigned to in methods that can be transitively called from non-private (non-constructor) methods.
****

The analyser annotates with {final} in the latter case; there is no point in cluttering with an annotation when the modifier is already there.
It annotates fields that are not effectively final with {variable}.

This definition allows effectively final fields to be assigned in methods accessible only from the constructor:

.Example {counter:example}, effectively final, but not with the `final` modifier
[source,java]
----
class EffectivelyFinal1 {
    @Final
    private Random random;

    public EffectivelyFinal1() {
        initialize(3L);
    }

    private void initialize(long seed) {
        random = new Random(seed);
    }

    // no methods access initialize()

    public int nextInt() {
        return random.nextInt();
    }
}
----

Obviously, if the same method is also accessible after construction, the field becomes variable:

.Example {counter:example}, the method setting the field is accessible after construction
[source,java]
----
class EffectivelyFinal2 {
    @Variable
    private Random random;

    public EffectivelyFinal2() {
        reset();
    }

    public void reset() {
        initialize(3L);
    }

    private void initialize(long seed) {
        random = new Random(seed);
    }

    public int nextInt() {
        return random.nextInt();
    }
}
----

Note that it is perfectly possible to rewrite the first example in such a way that the `final` modifier can be used.
From the point of view of the analyser, this does not matter.
The wider definition will allow for more situations to be recognized for what they really are.

When an object consists solely of primitives, or deeply immutable objects such as `java.lang.String`, having all fields effectively final is sufficient to generate an object that is again deeply immutable.

.Example {counter:example}, an object consisting of primitives and a string.
[[deeply-immutable1]]
[source,java]
----
class DeeplyImmutable1 {
    public final int x;
    public final int y;
    public final String message;

    public DeeplyImmutable1(int x, int y, String message) {
        this.message = message;
        this.x = x;
        this.y = y;
    }
}
----

.Example {counter:example}, another way of being effectively final
[source,java]
----
class DeeplyImmutable2 {
    @Final
    private int x;
    @Final
    private int y;
    @Final
    private String message;

    public DeeplyImmutable2(int x, int y, String message) {
        this.message = message;
        this.x = x;
        this.y = y;
    }

    public String getMessage() {
        return message;
    }

    public int getX() {
        return x;
    }

    public int getY() {
        return y;
    }
}
----

Examples 3 and 4 are functionally equivalent: there is no way of changing the values of the fields once they have been set.
In the real world there may be a reason why someone requires the getters.
Or, you may be given code as in Example 2, but you are not allowed to change it.
Whatever the reason, the analyser should recognize effective finality.

Note that we will not make a distinction between any of the different non-private access modes in Java.
Only the private modifier gives sufficient guarantees that no reassignment to the fields is possible.

We now have observed that for the purpose of defining immutability, having all your fields effectively final can be sufficient in certain, limited circumstances.
The analyser annotates types whose fields are all effectively final with {finalFields}.

Types that are not {finalFields} because they have at least one {variable} field, are annotated either {mutableModifiesArguments} or {container}, depending on properties of the methods' parameters to be explained later.

Note that as of more recent versions of Java, the `record` type enforces explicitly final fields, along with additional support for equality and visibility.
Any `record` will be at least {finalFields}.

We will in this work make a distinction between a property being _effectively_ or _eventually_ present.
The former indicates a property as computed after construction of the object, which is potentially a little broader than the definition of the language.
The latter is used when this property can only be obtained after the code reaches a certain state.
More on this later, but here is a first example of type with eventually final fields:

.Example {counter:example}, simplified version of `SetOnce`
[source,java]
----
@FinalFields(after="t")
class SetOnce<T> {
    private T t;

    @Mark("t")
    public void set(T t) {
        if(t == null) throw new NullPointerException();
        if(this.t != null) throw new IllegalStateException("Already set");
        this.t = t;
    }

    @Only(after="t")
    public void get() {
        if(this.t == null) throw new IllegalStateException("Not yet set");
        return this.t;
    }
}
----

Once a value has been set, the field `t` cannot be assigned anymore.

We have just observed that if one restricts to primitives and types like `java.lang.String`, final fields are sufficient to guarantee deep immutability.
It is not feasible, and we do not wish to, work _only_ with deeply immutable objects.
Moreover, it is easy to see that final fields alone not enough to guarantee what we intuitively may think immutability stands for:

.Example {counter:example}, final fields do not guarantee intuitive immutability
[source,java]
----
@FinalFields
class StringsInArray {
    private final String[] data;
    public StringsInArray(String[] strings) {
        this.data = strings;
    }
    public String getFirst() {
        return data[0];
    }
}

...
String[] strings = { "a", "b" };
StringsInArray sia = new StringsInArray(strings);
Assert.assertEquals("a", sia.getFirst());
strings[0] = "c"; // <1>
Assert.assertEquals("c", sia.getFirst()); // <2>
----

<1> External modification of the array.
<2> As a consequence, the data structure has been modified.

To continue, we must first understand the notion of modification.
