[#hidden-content]
== Hidden content

In this section, we consider modifications to the hidden content of a type, and explain when they are of importance.
We give a formal definition of deeply or recursively immutable types, introduce the annotation {ercontainer}, as well as a sliding scale between level 2 and recursively immutable.
The annotation {independent1}, which we have touched upon earlier earlier, will be formally introduced.

=== Visitors

Let's start by going back to `NonEmptyImmutableList`, first defined in <<abstract-methods>>:

.Example {counter:example}, revisiting `NonEmptyImmutableList`
[source,java]
----
@E2Container
interface NonEmptyImmutableList<T> extends HasSize {

    // implicitly present: @NotModified
    @Independent1
    T first();

    // implicitly present: @NotModified
    void visit(@Independent1 Consumer<T> consumer); // @IgnoreModifications

    @NotModified
    @Override
    default boolean isEmpty() {
        return false;
    }
}
----

We start the discussion with the following level 2 immutable implementation of this interface:

.Example {counter:example}, level 2 immutable implementation of `NonEmptyImmutableList`
[source,java]
----
@E2Container
class ImmutableOne<T> implements NonEmptyImmutableList<T> {
    private final T t;

    public ImmutableOne(@Independent1 T t) {
        this.t = t;
    }

    @Override
    public int size() {
        return 1;
    }

    @Override
    public T first() {
        return t;
    }

    @Override
    public void visit(Consumer<T> consumer) {
        consumer.accept(t);
    }
}
----

We need the `visit` method (1) to be non-modifying, and (2) not to modify its parameter `consumer`.
However, following the normal definitions of modification, the following two statements hold:

1. Because `accept` is {modified}, we should mark the parameter `consumer` as {modified}.
2. Because `t`, the parameter of `accept`, is {modified}, we should mark `visit` as {modified}.

The result of the first statement would violate the `@Container` property on `ImmutableOne`, and we'd be very reluctant to do that:
according to the intuitive definition in <<containers>>, `ImmutableOne` is a type that holds data, but does not change it.
This statement still holds in the presence of a `visit` method, which is nothing but a way of exposing the object in a way similar to the method `first`.
The second one would make `visit` modifying, which again goes against our intuition: looping over elements is, in itself, not modifying.

Luckily, there are two observations that come to the rescue.

First, we believe it is correct to assume that concrete implementations of `Consumer` can be semantically unrelated to `ImmutableOne`.
As a consequence, we could say that the only modifications that concern us in this `visit` method are the modifications to `accept` 's parameter `t`.
Other modifications, for example those to the fields of the type in which the implementation is present, may be considered to be outside our scope.
However, if we replace `Consumer` with `Set` and `accept` with `add`, we encounter a modification that we really do not want to ignore, in an otherwise equal setting.
Therefore, it does not look like we can reason away potential modifications by `accept`.
We will have to revert to a contracted {ignoreModifications} annotation on the parameter `consumer`, if we want to avoid `ImmutableOne` losing the `@Container` property.

The second modification, however, is one we will ignore in the `ImmutableOne` type, and _defer_ or _propagate_ to the place where a concrete implementation of the consumer is presented.
We can ignore it here, because `t` is part of the hidden content of the type; what happens to its content happens outside the zone of control of `ImmutableOne`.
The fact that it is passed as an argument to a method of `consumer` is reflected by the {independent1} annotation.
It will take care of the propagation of modifications from the concrete implementation into the hidden content.

This results in the following annotations for `visit` in `ImmutableOne`:

.Example {counter:example}, the `visit` method in `ImmutableOne`, fully annotated
[source,java]
----
@NotModified
public void visit(@IgnoreModifications @Independent1 Consumer<T> consumer) {
    consumer.accept(t);
}
----

Note that we assume that we will need {ignoreModifications} for almost every use of a functional interface from `java.util.function` occurring as a parameter.
These types are for generic use; one should never use them to represent some specific data type where modifications are of concern to the current type.
Therefore, we make this annotation implicit in exactly this context.

IMPORTANT: A parameter of formal functional interface type will be marked {ignoreModifications} implicitly.

Looking at the more general case of a `forEach` implementation iterating over a list or array, we therefore end up with:

.Example {counter:example}, a generic `forEach` implementation
[source,java]
----
@NotModified
public void forEach(@Independent1 Consumer<T> consumer) {
    for(T t: list) consumer.accept(t);
}
----

Modifications to the parameter, made by the concrete implementation, are propagated into the hidden content of `list`, as shown in the next section.
The {independent1} annotation appears because hidden content in `list` is exposed to the `consumer` parameter.
This annotation does not appear for the accessible content of the level 2 immutable type.
Parameters of modifiable type are already shielded from external modification by the {independent} annotation, which is "trivial" for level 2 immutable types.

=== Propagating modifications

Let us apply the `visit` method of `NonEmptyImmutableList` to `StringBuilder`:

.Example {counter:example}, propagating the modification of `visit`
[source,java]
----
static void print(@NotModified NonEmptyImmutableList<StringBuilder> list) {
    one.visit(System.out::println); // <1>
}

static void addNewLine(@Modified NonEmptyImmutableList<StringBuilder> list) {
    one.visit(sb -> sb.append("\n")); // <2>
}
----

<1> Non-modifying method implies no modification on the hidden content of `list`.
<2> Parameter-modifying lambda propagates a modification to `list` 's hidden content.

It is the second method, `addNewLine`, that is of importance here.
Thanks to the {independent1} annotation, we know of a modification to `list`, even if `list` is of level 2 immutable type!
It may help to see the for-loop written out, if we temporarily assume that we have added an implementation of `Iterable` to `NonEmptyImmutableList`, functionally identical to `visit`:

.Example {counter:example}, alternative implementation of `addNewLine`
[source,java]
----
static void addNewLine(@Modified NonEmptyImmutableList<StringBuilder> list) {
    for(StringBuilder sb: list) {
      sb.append("\n"));
    }
}
----

We really need the link between `sb` and `list` for the modification on `sb` to propagate to `list`.
Without this propagation, we would not be able to implement the full definition of modification of parameters, as stipulated in <<modification>>, in this relatively straightforward, and probably frequently occurring situation.

Moving from `NonEmptyImmutableList` to `NonEmptyList`, defined <<NonEmptyList, here>>, which has a modifying method, allows us to contrast two different modifications:

.Example {counter:example}, contrasting the modification on the parameter `sb` to that on `list`
[source,java]
----
static void addNewLine(@Modified NonEmptyList<StringBuilder> list) {
    list.visit(sb -> sb.append("\n")); // <1>
}

static void replace(@Modified NonEmptyList<StringBuilder> list) {
    list.setFirst(new StringBuilder("?")); // <2>
}
----

<1> Modification to the hidden content of `list`
<2> Modification to the modifiable content of `list`

Without storing additional information (e.g., using an as yet undefined annotation like `@Modified1` on `list` in `addNewLine`), however, we cannot make the distinction between a modification to the string builders inside `list`, or a modification to `list` itself.
In other words, applying the two methods further on, we cannot

.Example {counter:example}, using `print` and `addNewLine`
[source,java]
----
static String useAddNewLine(@NotModified StringBuilder input) { // <1>
    NonEmptyList<StringBuilder> list = new One<>();
    list.setFirst(input);
    addNewLine(list);
    return list.getFirst().toString();
}

static String useReplace(@NotModified StringBuilder input) {
    NonEmptyList<StringBuilder> list = new One<>();
    list.setFirst(input);
    replace(list); // <2>
    return list.getFirst().toString();
}
----

<1> Should be {modified}, however, in the 3rd statement we cannot know that the modification is to `input` rather than to `list`
<2> This action discards `input` from `list` without modifying it.

****
The example shows that the introduction of {independent1} only gets us so far: from the concrete, modifying implementation, to the parameter (or field).
We do not plan to keep track of the distinction between modification of hidden content vs modification of modifiable content to a further extent.
****

Finally, we mention again the modification to a field from a concrete lambda:

.Example {counter:example}, modification of a field outside the scope
[source,java]
----
List<String> strings = ...
@Modified
void addToStrings(@NotModified NonEmptyList<StringBuilder> list) {
  list.visit(sb -> strings.add(sb.toString()));
}
----

[#hidden-content-linking]
=== Hidden content linking

Going back to `ImmutableOne`, we see that the constructor links the parameter `t` to the instance's field by means of assignment.
Let us call this binding of parameters of hidden content to the field _content linking_, and mark it using {independent1}, _content dependence_:

.Example {counter:example}, constructor of `ImmutableOne`
[source,java]
----
private final T t;

public ImmutableOne(@Independent1 T t) {
    this.t = t;
}
----

Returning a part of the hidden content of the type, or exposing it as argument, both warrants a {independent1} annotation:

.Example {counter:example}, more methods of `ImmutableOne`
[source,java]
----
@Independent1
@Override
public T first() {
    return t;
}

@Override
public void visit(@Independent1 Consumer<T> consumer) {
    consumer.accept(t);
}
----

Observe that content dependence implies absence of dependence, as described in <<linking-and-independence>> and <<computing-dependence>>, exactly because we are dealing with parameters of level 2 immutable type.

Another place where the hidden content linking can be seen, is the _for-each_ statement:

.Example {counter:example}, for-each loop and hidden content linking
[source,java]
----
ImmutableList<StringBuilder> list = ...;
List<StringBuilder> builders = ...;
for(StringBuilder sb: list) {
    builders.add(sb);
}
----

Because the `Collection` API contains an `add` method annotated as:

.Example {counter:example}, `add` in `Collection` annotated
[source,java]
----
@Modified
boolean add(@NotNull @Independent1 E e);
----

indicating that after calling `add`, the argument will become part of the hidden content of the collection, we conclude that the local loop variable `sb` gets content linked to the `builders` list.
Similarly, this loop variable contains hidden content from the `list` object.

We reuse the annotation {independent1} to indicate that the hidden content of two objects are linked.
Let us look at a possible implementation of `Collection.addAll`:

.Example {counter:example}, a possible implementation of `addAll` in `Collection`
[source,java]
----
@Modified
boolean addAll(@NotNull1 @Independent1 Collection<? extends E> collection) {
    boolean modified = false;
    for (E e : c) if (add(e)) modified = true;
    return modified;
}
----

The call to `add` content links `e` to `this`.
Because `e` is also content linked to `c`, the parameter `collection` holds hidden content linked to the hidden content of the instance.

We are now properly armed to see how a for-each loop can be implemented using an iterator whose hidden content links to that of a level 1 immutable container.

=== Iterator, Iterable, loops

Let us start with the simplest definition of an iterator, without `remove` method:

.Example {counter:example}, the `Iterator` type, without `remove` method
[source,java]
----
@E1Container
interface Iterator<T> {

    @Modified
    @Independent1
    T next();

    @Modified
    boolean hasNext();
}
----

Either the `next` method, or the `hasNext` method, must make a change to the iterator, because it has to keep track of the next element.
As such, we make both {modified}.
Following the discussion in the previous section, `next` is {independent1}, because it returns part of the hidden content held by the iterator.

The interface `Iterable` is a supplier of iterators:

.Example {counter:example}, the `Iterable` type
[source,java]
----
@E2Container
interface Iterable<T> {

    @Independent1
    Iterator<T> iterator();
}
----

First, creating an iterator should never be a modifying operation on a type.
Typically, as we explore in the next section, it implies creating a sub-type, static or not, of the type implementing `Iterable`.
Second, the iterator itself is independent of the fields of the implementing type, but has the ability to return its hidden content.

The loop, on a variable `list` of type implementing `Iterable<T>`, is expressed as `for(T t: list) { ... }`, and can be interpreted as

.Example {counter:example}, implementation of for-each using an `Iterator`
[source,java]
----
Iterator<T> it = list.iterator();
while(it.hasNext()) {
    T t = it.next();
    ...
}
----

The iterator `it` content-links to `list`; via the `next` method, it content-links the hidden content of the `list` to `t`.

=== Eventual immutability

How does the whole story of eventual level 1 or level 2 immutability mix with hidden content?
At some point, once a necessary precondition has been met, the hidden content will be well-defined, and modifying methods become unavailable.
Before that, fields that will eventually contain the hidden content may still be `null`, or may be re-assigned.
This should not have any effect, however, on the computation of hidden content linking, {independent1} annotations, and the propagation of modifications, since the actual types do not change.
The two concepts are sufficiently perpendicular to each other, and can easily co-exist.

//end of file