[#preconditions-and-instance-state]
== Preconditions and instance state

The {e2immu} analyser needs pretty strong support for determining preconditions on methods to be able to compute eventual immutability.
A lot of the mechanics involved can be harnessed in other ways as well, for example, to detect common mistakes in the use of collection classes.

We have implemented a system where the value of a variable can be augmented with _instance state_ each time a method operates on the variable.
In the case of Java collections and `StringBuilder`, size-based instance state is low-hanging fruit.
Let's start with an example:

.Example {counter:example}, creating an empty list
[source,java]
----
List<String> list = new ArrayList<>();
if (list.size() > 0) { // WARNING: evaluates to constant
    ...
}
----

When creating a new `ArrayList` using the empty constructor, we can store in the variable's value that its size is 0.
First, let us look at the annotations for the `size` method:

.Example {counter:example}, annotations of `List.size`
[source,java]
----
void size$Aspect$Size() {}
boolean size$Invariant$Size(int i) { return i >= 0; }
@NotModified
int size() { return 0; }
----

The method has two _companion methods_.
The first registers `Size` as a numeric _aspect_ linked to the `size` method.
The second adds an invariant (an assertion that is always true) in relation to the aspect: the size is never negative.

Looking at the annotations for the empty constructor,

.Example {counter:example}, annotations of empty `ArrayList` constructor
[source,java]
----
boolean ArrayList$Modification$Size(int post) { return post == 0; }
public ArrayList$() { }
----

we see another companion method, that expresses the effect of the construction in terms of the `Size` aspect.
(The dollar sign at the end of the constructor is an artifact of the annotated API system; please refer to the {e2immu} manual.) Internally, we represent the value of `list` after the assignment as

.Example {counter:example}, internal representation of an empty list
[source,java]
----
new ArrayList<>()/*0==this.size()*/
----

The expression in the companion results in the fact that the `Size` aspect post-modification is 0.
This then gets added to the evaluation state, which allows the analyser to conclude that the expression in the if-statement is a constant true.

This approach is sufficiently strong to catch a number of common problems when working with collections.
After adding one element to the empty list, as in:

.Example {counter:example}, adding an element to an empty list
[source,java]
----
List<String> list = new ArrayList<>();
list.add("a");
----

the value of `list` becomes

.Example {counter:example}, internal representation after adding an element
[source,java]
----
instance type ArrayList<String>/*this.contains("a")&&1==this.size()*/
----

The boolean expression in the comments is added to the evaluation state, so that expressions such as `list.isEmpty()`, defined as:

.Example {counter:example}, `List.isEmpty` and its companion method
[source,java]
----
boolean isEmpty$Value$Size(int i, boolean retVal) { return i == 0; }
@NotModified
boolean isEmpty() { return true; }
----

can be evaluated by the analyser.
We refer to the manual for a more in-depth treatment of companion methods and instance state.