== Appendix

=== Immutability and independence

Immutability requires three properties:

. the fields are effectively final
. there are no modifying methods
. there is independence of method return values and parameters

Only when all three are satisfied, we reach immutability.
The first table shows which annotations are used in function of the presence of these three properties.
The reason we add {finalFieldsAbsent}, {independentAbsent} and {modified} is to indicate to the user that there is only one property missing to reach immutability.

.Leading up to immutability
[cols="5"]
|===

h|
2+^h|variable fields
2+^h|(eventually) final fields

h|
h|dependent
h|independent
h|dependent
h|independent

h|modifying methods
|no annotation (variable, dependent, modified)
|no annotation (variable, modified)
|{finalFields}
|{finalFields}{modified}

h|no modifying methods
|no annotation (variable, dependent)
|`@FinalFields(absent=true)`
|{finalFields}{independentAbsent}
|{immutable}

|===

Immutability comes in three different forms: with or without hidden content, and, when without, constant or not constant.
Because of the importance and hopefully abundant presence of the container property, we combine both annotations.

.Different forms of immutability
[cols="4"]
|===

h|type has
^h|hidden content
2+^h|no hidden content

h|type is
h|
h|not constant
h|constant

h|type is not container
|`@Immutable(hc=true)`
|`@Immutable`
|`@Immutable(value="abc")`

h|type is container
|`@ImmutableContainer(hc=true)`
|`@ImmutableContainer`
|`@ImmutableContainer(value="abc")`

h|independence
|{independentHC} or {independent}
2+^|{independent}
|===

The independence levels are

* dependent: modification of communicated values potentially implies a change to the accessible part of the object graph of the fields
* independent: defined as not dependent.
When required, this can be split into
** allow hidden content transfer, or `hc = true`: modification of communicated values potentially implies a change to the hidden part of the object graph of the fields, but not in the accessible part
** don't allow any transfer, or `hc = false`: modification of communicated values is either impossible or cannot change to the object graph of the fields

.Possible combinations of dependence of communicated values in relation to immutability
[cols=4]
|===

h|type
^h|not immutable
2+^h|immutable

h|type has
h|
^h|hidden content
^h|no hidden content

h|dependent (no annotation)
^|{y}
^|{n}
^|{n}

h|{independentHC}
^|{y}
^|{y}
^|{n}

h|{independent}
^|{y}
^|{y}
^|{y}

|===

=== Default annotations

When annotating abstract types, or types in the Annotated APIs, observe the following rules.

A method is {nm} unless otherwise specified, its parameters are assumed to be {modified}.

The annotations {container} and {independent} on types are essentially shorthands to avoid having to write, respectively and where applicable, {nm} on parameters, and {independent} on parameters and methods.
Their values on types are computed by the analyser after processing the other information about the type, and the annotations on methods and parameters.

In a {container} type, all {fluent} methods and all void methods are assumed to be {modified}.
Change this by explicitly marking the method {nm} or {sse}.

Parameters of a non-modifying method are {independent} by default, regardless of an independence annotation on the type.
This can be overwritten by {independentAbsent} or {independentHC} when the method 'leaks' content via its parameters.

When a type is not immutable, dependence is the normal state for methods, parameters and types.
It is only explicitly written as {independentAbsent} on a type after analysis, when this type has (eventually) final fields and no modifying methods, as a marker to the user to indicate which property is missing to reach immutability.
Marking a non-immutable type with {independent} specifies that no parameter or return value can be dependent.
The hidden content parameter given by the user is ignored: you will still have to mark any method or parameter which communicates hidden content with {independentHC}.

When a type is immutable, {independent} becomes the default independence annotation for methods and parameters.
You must still use {independentHC} to indicate communication of hidden content.

The analyser computes the final independence value of the type by inspecting the methods and their parameters.

Methods marked {fluent} are always {independent}, because returning the type itself does not expose any additional information.

Following its definition, a {utilityClass} implies {immutable}.

In the {immutable} annotation, we generally do not write `hc = false`, as that is the default value in the annotation.
The analyser adds `hc = true` automatically when a type is abstract (it is an interface, or an abstract class).
It will complain when `hc = false` is present on an abstract type.

In application mode, the analyser will regard every class that is never extended as effectively final.
This property is only relevant when the type is immutable; the absence of `hc = true` is a marker.

Parameters of "official" functional interface type (i.e., the type is a functional interface type in the package `java.util.function`) have the {ignoreModifications} annotation, unless explicitly overwritten by {modified}.

The default nullable annotation for parameters and return values of non-primitive type is {nullable}.

A factory method is a static method returning an object of the type of the class.
Independence of a factory method is always with respect to the method's parameters, rather than to the type.
This rule applies to any static method in a immutable type.
(Utility classes are classes that are immutable and cannot be instantiated.)