name: github pages

on:
  push:
    branches:
      - main 

jobs:
  build_and_copy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup java 
        uses: actions/setup-java@v1
        with:
            java-version: 16

      - name: generate html files using gradle
        uses: eskatos/gradle-command-action@v1
        with:
            arguments: asciidoctor

      - name: generate PDF files using gradle
        uses: eskatos/gradle-command-action@v1
        with:
            arguments: asciidoctorPdf
              
      - name: copy generated documentation files to e2immu-site
        env:
          REPO: e2immu/e2immu-site
          SOURCE: build/docs/asciidoc/
          TARGET: target/static/docs
          GIT_USERNAME: action
          GIT_EMAIL: action@github.com
        run: |
            git clone https://.:${{ secrets.GTOKEN }}@github.com/${{ env.REPO }} target
            if [ -d ${{ env.TARGET }} ]; then rm -rf ${{ env.TARGET }}/*; fi
            cp -r ${{ env.SOURCE }}* ${{ env.TARGET }}/
            cd target
            git config --local user.email "${{ env.GIT_EMAIL }}"
            git config --local user.name "${{ env.GIT_USERNAME }}"
            git add .
            git commit -m "Github actions automatic build - `date +"%Y-%m-%d %H:%M"`"
            git push origin --set-upstream main
            

