name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
            java-version: 16

      - uses: eskatos/gradle-command-action@v1
        with:
            arguments: asciidoctor

